package com.app.jzapp.videoapp.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.app.jzapp.videoapps.bean.DownLoadBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downLoadBeanDaoConfig;

    private final DownLoadBeanDao downLoadBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downLoadBeanDaoConfig = daoConfigMap.get(DownLoadBeanDao.class).clone();
        downLoadBeanDaoConfig.initIdentityScope(type);

        downLoadBeanDao = new DownLoadBeanDao(downLoadBeanDaoConfig, this);

        registerDao(DownLoadBean.class, downLoadBeanDao);
    }
    
    public void clear() {
        downLoadBeanDaoConfig.clearIdentityScope();
    }

    public DownLoadBeanDao getDownLoadBeanDao() {
        return downLoadBeanDao;
    }

}
